[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200