[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NETLIFY_USE_YARN = "false"

# Redirects untuk static export
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Fallback untuk SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200