[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Plugin NextJS dihapus karena menyebabkan konflik dengan static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Redirects untuk static export
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Jangan redirect dynamic routes ke index
# [[redirects]]
#   from = "/news/*"
#   to = "/news/index.html"
#   status = 200

# Fallback untuk SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200