[build]
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "src"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirects untuk static export
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Fallback untuk SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200