[build]
  command = "npm run build"
  publish = "out"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "src"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PRIVATE_TARGET = "serverless"

# Plugin untuk Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects untuk static export
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Jangan gunakan fallback SPA untuk Next.js
# Biarkan Next.js menangani routing