[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8.19.3"
  NEXT_PRIVATE_TARGET = "server"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200